### ISSUE TITLE
[feature]: Edge-Associated Path Cost Analysis for Optimal Routing in Knowledge Graphs

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/internet-yellow-pages#108]
## Feature Description
Happy New Year everyone 🎄 I'm wondering if there are any associated path costs linked to the edges in our knowledge graph? Understanding and identifying these costs would enable the development of highly beneficial applications on our knowledge graph. This is particularly valuable for network operators, e.g. facilitating the identification of optimal paths between Autonomous Systems (ASes - source and destination). It involves employing the traditional optimal graph traversal algorithms.

**Key Node Labels in our Knowledge Graph where the optimal path may be helpful (not exhaustive):**
- `AS`
- `Prefix`
- `IP`
- `Country`
- `PeeringdbOrgID`
- `Organization`
- `Name`
- `Ranking`
- `BGPCollect`
- `Facility`
- `PeeringdbFacID`
- `PeeringdbIXID`
- `IXP`
- `PeeringdbNetID`
- `AuthoritativeNameServer`

**Comment by m-appel** [comment]
Hey,

I don't think I fully understand what you mean with path costs in the context of our knowledge graph, so correct me if I'm wrong.
What you say sounds a bit like the path-cost attributes seen in routing (e.g., BGP), but these do not really apply to our graph. We have an `AS peers with AS` relationship, but this is based on the AS paths visible by route collectors, which are already the best paths selected by their peers. In other words, we do not have a full view of all available paths so we can't (and don't want to) run any path optimization algorithms on our knowledge graph.

**Comment by mohamedawnallah** [comment]
Yes exactly I was referring to the path/edges cost attributes but you're right this is not feasible in our knowledge graph.
