### ISSUE TITLE
Better formatting checks for IP, prefixes, and countries

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/internet-yellow-pages#112]
Currently we make sure that all IPs and prefixes are in lower case. And also that country codes are in upper case. We still need the crawlers to take care of IPv6 compression and we hope they give well-formed IP, prefixes, and country codes but unexpected things can still happen.

https://github.com/InternetHealthReport/internet-yellow-pages/blob/98f970100ec30ea61a0eaff8258629c3af0b279c/iyp/__init__.py#L15-L23

Why not adding the checks in the iyp library too?
For example:
```python
prop_formatters = { 
     # asn is stored as an int 
     'asn': int, 
     # ipv6 is stored in lowercase 
     'ip': lambda s: ipaddress.ip_address(s).compressed, 
     'prefix': lambda s: ipaddress.ip_network(s).compressed, 
     'country_code': lambda s: iso3166.countries.get(s).alpha2
 }
```

Yes, it is redundant, the crawlers still have to do that too, but at least we ensure that no weird node are created.
@m-appel did we have any good reason for not adding these checks in iyp/__init__.py?

**Comment by m-appel** [comment]
Nope, this is actually just this issue #87, which we have not implemented yet :) The fix is fast, but needs some careful checking if affected crawlers still work correctly.

**Comment by romain-fontugne** [comment]
Thanks, I'll try a full run with the code mentioned above and see if things break.

**Comment by romain-fontugne** [comment]
ok, for the records, that broke quite a few crawlers. This is the log:
[iyp-2024-01-17.log](https://github.com/InternetHealthReport/internet-yellow-pages/files/14004447/iyp-2024-01-17.log)

**Comment by m-appel** [comment]
Good thing we tested it :) For the ones that break due to the IP address/network, I think they should be fixed, but I think forcing an ISO3166 country code might be a bit much? I know `ZZ` for example is technically a correct "Reserved" country code...

**Comment by romain-fontugne** [comment]
Agreed, we should tolerate also the exotic country codes (EU, AP). But no weird IP should go through these checks.

**Comment by Forchapeatl** [comment]
I would love to work on this issue.
