### ISSUE TITLE
Download compressed ROA file in `crawlers.ripe.roa`

### ISSUE THREAD

**Issue by m-appel** [InternetHealthReport/internet-yellow-pages#117]
After February 12th, the `roas.csv` file we fetch from RIPE's FTP server will no longer be available in an uncompressed format (see [here](https://www.ripe.net/ripe/mail/archives/routing-wg/2024-January/004812.html)).
Instead we need to download (and handle) the compressed `roas.csv.xz` file.

**Comment by romain-fontugne** [comment]
ah, I forgot about this crawler... related to this we updated the code for the route-origin-validation library: 
https://github.com/InternetHealthReport/route-origin-validator/commit/dc8e0b54cae65d5307e8a85294df7cfc2f025c8d

we could reuse these modifications

**Comment by MAVRICK-1** [comment]
@m-appel I have already solved this issue :-)

**Comment by romain-fontugne** [comment]
@MAVRICK-1 we also have to fix the issue here: https://github.com/InternetHealthReport/internet-yellow-pages/blob/9cf01c53e16c6d9f5be7395a157d49609a2bf7dc/iyp/crawlers/ripe/roa.py#L43-L54

**Comment by MAVRICK-1** [comment]
> @MAVRICK-1 we also have to fix the issue here: https://github.com/InternetHealthReport/internet-yellow-pages/blob/9cf01c53e16c6d9f5be7395a157d49609a2bf7dc/iyp/crawlers/ripe/roa.py#L43-L54

Sir , I was referring to this https://github.com/InternetHealthReport/route-origin-validator/commit/dc8e0b54cae65d5307e8a85294df7cfc2f025c8d in route-origin-validator.
:- ).

**Comment by romain-fontugne** [comment]
yes, let's just reuse the same code

**Comment by MAVRICK-1** [comment]
> yes, let's just reuse the same code

If I am not wrong Then
https://github.com/InternetHealthReport/internet-yellow-pages/blob/9cf01c53e16c6d9f5be7395a157d49609a2bf7dc/iyp/crawlers/ripe/roa.py#L52-L68

this code fetches data from a RIPE ROA file, processes the CSV content line by line, extracts relevant information, and aggregates the data into a dictionary (prefix_info). This dictionary is structured with prefixes as keys, and each prefix key has a list of dictionaries associated with it, containing information about URLs, ASNs, and other details for that prefix.

As https://ftp.ripe.net/rpki/apnic.tal/2023/11/06/ contains output.json.xz file we can decompress it and use that.

**Comment by m-appel** [comment]
The `output.json.xz` file does not contain the validity period of the ROA, which we would like to keep, so let's use `roas.csv.xz`.
