### ISSUE TITLE
Replace use of `id()` with `elementId()`

### ISSUE THREAD

**Issue by m-appel** [InternetHealthReport/internet-yellow-pages#154]
The [`id()`](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-id) function we use in our [main module](https://github.com/InternetHealthReport/internet-yellow-pages/blob/280243d10cc291cb7ac1241c914c40d2e16b46c8/iyp/__init__.py) is deprecated and should be replaced with [`elementId()`](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-elementid). I believe it's just a matter of replacing the function, but should be confirmed.

Newer versions of the neo4j Python module will raise a lot of warnings so we should address this at some point.

**Comment by ronibhakta1** [comment]
Hey @m-appel if you want me to handle this i would like to work on this to make changes in as you required !
You can assign this to me so that i can work on this..

**Comment by m-appel** [comment]
Hi, sure you can work on this. Like I wrote, the actual code changes are probably simple, but you should confirm that all changed functions still behave the same.
