### ISSUE TITLE
Remove/Transform Wikidata leftovers

### ISSUE THREAD

**Issue by m-appel** [InternetHealthReport/internet-yellow-pages#23]
There are some Wikidata files left that should be removed and some of the crawlers need to be refactored for neo4j usage.

**Comment by Bhardwaj-Himanshu** [comment]
Hi @m-appel,
If this issue is still open and you need some help, I would love to do so.

I had some queries before proceeding towards the issue:
-could you please provide a link or more details over where this data exactly is located?

Thanks

**Comment by SAHELISAHAA** [comment]
@m-appel is this issue still open ?
can i work on this ?

**Comment by romain-fontugne** [comment]
I believe now this is just a matter of deleting old files. I just checked and the only crawlers we haven't migrated are either outdated (e.g. rapid7 that is not public anymore) or have been replaced (e.g. bgp is not needed anymore, we get that data from bgpkit and hoping to soon get spamhaus via firebog)
