### ISSUE TITLE
Error when setting up IYP using docker

### ISSUE THREAD

**Issue by roopeshsn** [InternetHealthReport/internet-yellow-pages#29]
An error was thrown by docker when setting up IYP by running the command `docker-compose up`. Here's the error message,

```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.iyp.depends_on contains an invalid type, it should be an array
```

The issue is that version 3 no longer supports the condition form of depends_on. Here's the compose file structure, https://docs.docker.com/compose/compose-file/compose-file-v3/#:~:text=Compose%201.27.0%2B.-,Compose%20file%20structure%20and%20examples,-%F0%9F%94%97

**Comment by thisiskaransgit** [comment]
Hey, @roopeshsn is this issue still there?

It's working fine on my machine

Looks like it has to do with the compose version, `docker-compose`  command belongs to compose v1, which is not supported anymore, it had this issue in it. 

It has been replaced with compose v2, which you can execute with the command `docker compose`.

Follow these steps to install it :

https://docs.docker.com/compose/install/ 

and then try running the image with `docker compose up`

**Comment by romain-fontugne** [comment]
yes, I also use ```docker compose up```.
We should probably update the readme to avoid confusion

**Comment by m-appel** [comment]
I just tried the setup in a clean VM and with the current instructions it works, so considering this closed.
