### ISSUE TITLE
Data Not Writable 

### ISSUE THREAD

**Issue by thisiskaransgit** [InternetHealthReport/internet-yellow-pages#31]
Currently, we are getting this Warning while running the database,  also this is affecting the connection while we are running the interface, it shows an error when trying to access the database 

`iyp_loader  | Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.`
 
Is the /data directory had to be restricted?

cc: @romain-fontugne

**Comment by romain-fontugne** [comment]
I think this is not a problem, the warning just say that the owner of that directory is changed but anyways the user is not suppose to touch that directory

**Comment by romain-fontugne** [comment]
I'm closing this for now but let me know if this really bother you
