### ISSUE TITLE
Email alert if an error happened during create_db script

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/internet-yellow-pages#36]
**Is your feature request related to a problem? Please describe.**
Currently we create a new database every week using a cron job. Since this project requires access to a lot of third party datasets, there is quite some chance that a crawler fails. It would be nice to have the possibility to alert by email if something went wrong, so that someone can manually restart the failing crawlers.

**Describe the solution you'd like**
Add an email  and smtp credentials field in the config file and send an email if an exception was caught during the create_db script.

**Comment by roopeshsn** [comment]
That's a nice addition to IYP. I would like to work on this.

**Comment by roopeshsn** [comment]
We can close this issue @romain-fontugne
