### ISSUE TITLE
Anycast prefixes from bgp.tools

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/internet-yellow-pages#42]
Implement a crawler (in iyp/crawlers/bgptools) that fetch the IPv4 and IPv6 prefixes reported here:
https://github.com/bgptools/anycast-prefixes

The added relationships should look like this (:Prefix)-[:Categorized]->(:Tag {label:Anycast})

**Comment by roopeshsn** [comment]
Shall I work on this @romain-fontugne

**Comment by romain-fontugne** [comment]
yes, please. Thanks!
