### ISSUE TITLE
Emile's crowdsourced ASnames added

### ISSUE THREAD

**Issue by emileaben** [InternetHealthReport/internet-yellow-pages#46]
**Explain the dataset you want to add and how it would contribute to the Internet Yellow Pages.**
I'm "crowdsourcing" ASnames. Currently this is just a single file that I accept edits on. It is at: https://github.com/emileaben/asnames

**Provide the name of the organization providing the data and the url to the dataset**
- Org name: Emile Aben
- URL: https://github.com/emileaben/asnames

space delimited file with 2 fields: field1 asn , field2 name
from commit history you might be able to derive who submitted the name (or I could add it explicitly)

Very experimental at the moment, but should provide short and useful AS names. Short because screen space is precious, esp. for viz

**If possible describe how you woud like to model the dataset in the Yellow Pages**
- Same as other 'names' datasets

**Comment by roopeshsn** [comment]
Hi, @emileaben! Currently the relationship between an `ASN` and the `AS name` is modeled like this,

```
MATCH (a:AS {asn: 15378})-[r:NAME]-(b:Name) RETURN a,b
```

![graph (10)](https://github.com/InternetHealthReport/internet-yellow-pages/assets/70762571/ef8039ab-cce7-42de-ab49-d62fdceb4537)

As you see the relationship, there are multiple relationships with the same variants of names for an `AS`. Whether this is done intentionally to have the variants of the name @romain-fontugne? We can follow the same for your dataset @emileaben. Also,

**Comment by emileaben** [comment]
Yes, an AS can have multiple names (depending on who recorded the naming).
Just like Farrokh Bulsara (his official name), is better known as Freddie
Mercury ( https://en.wikipedia.org/w/index.php?title=Farrokh_Bulsara ).

e

**Comment by emileaben** [comment]
Oh, and my dataset can make this (multiple names for same ASN) even worse,
it can have multiple names for the same ASN within the data-source. I've
also added a 'contributor' ID (for now that can be a property on the link
(or initially you can leave it out?)

e

**Comment by romain-fontugne** [comment]
Indeed, it is intentional to have multiple names for the same AS. 

@roopeshsn do you want to work on this? I guess the code will be similar to the crawler you just implemented.

**Comment by m-appel** [comment]
I would also propose to store the contributor in the relationship. So basically keep `reference_url: https://raw.githubusercontent.com/emileaben/asnames/main/asnames.csv` and annotate the `NAME` relationship with a `contributor` property like Emile said.

**Comment by romain-fontugne** [comment]
thanks!
