### ISSUE TITLE
create_db script should report an error if a crawler is not pushing any data

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/internet-yellow-pages#50]
**Describe the bug**
create_db reports no error if a crawler add no data to the database.

**To Reproduce**
Hard to reproduce but recently the AS relationships dataset from BGPKIT was empty.

**Expected behavior**
I would expect an error message in the create_db log (and email) so that we get informed about that.

**Comment by romain-fontugne** [comment]
ah, that's what our 'unit_test' methods are doing. Maybe we should call the unit_test methods in create_db?

**Comment by romain-fontugne** [comment]
Yes, that code needs some refactoring. The unit_test is not used, we rushed that during the preparation for gsoc...

I guess the most efficient would be either:
- to count the number of relationships in the create_db script. 
- or the run function should return the number of added relationships, and create_db can log an error if that number is 0.

**Comment by mohamedawnallah** [comment]
Issue Involvement:
I'm interested in working on this particular issue. There's one aspect I'd like to grasp – the necessity for all external crawler data to be non-empty. Could you please explain why this requirement exists? Additionally, I'm curious about the reason behind not implementing a graceful failure handling mechanism in cases where there's no data to push to the Neo4j database. By doing so, we could potentially avoid the need for error logging.

Specific Context:
I'm assuming you're talking specifically about the [Fetching phase within the create_db script](https://github.com/InternetHealthReport/internet-yellow-pages/blob/a075ba228e606091cab7ee9349cfca5509584fe0/create_db.py#L106C1-L125C22).

**Comment by romain-fontugne** [comment]
Sorry I have missed that one. Yes, we want to make sure that at each iteration in the for loop the number of nodes or links in the database is increasing.

**Comment by mohamedawnallah** [comment]
Addressed in this PR #76
