### ISSUE TITLE
Feature/Add IYP Guides

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/internet-yellow-pages#65]
Currently, there are no IYP Guides added in the main `README.md` file for `internet-yellow-pages` Adding it will help new contributors quickly become involved in the project.

**Comment by romain-fontugne** [comment]
addressed in #66

**Comment by romain-fontugne** [comment]
Sorry I merged this too quickly. Actually the guides don't render very well outside of the neo4j browser... I changed again the text in the readme. 
Still I think it is a valid issue. We are usually advertising the http://iyp.iijlab.net url but this goes straight to the neo4j browser. It would be nice to have a landing page with basic instructions and a button to the neo4j browser

**Comment by mohamedawnallah** [comment]
That's more nice and interactive. Thanks a lot for taking the suggestion and the initiative!!

**Comment by m-appel** [comment]
Romain reworked the https://iyp.iijlab.net/ domain (source available at [InternetHealthReport/iyp-website](https://github.com/InternetHealthReport/iyp-website)), I think that closes this issue?

**Comment by romain-fontugne** [comment]
agreed, I think this is addressed by the new website (https://iyp.iijlab.net/index.html), the code is here:
https://github.com/InternetHealthReport/iyp-website
