### ISSUE TITLE
Add network and prefixlen properties to Prefix nodes

### ISSUE THREAD

**Issue by m-appel** [InternetHealthReport/internet-yellow-pages#74]
We should add two properties to `Prefix` nodes that contain the network and prefix length explicitly to make some queries (e.g., most specific prefix) easier.

Current properties:
```
af: 4
prefix: 192.0.2.0/24
```

Desired properties:
```
af: 4
network: 192.0.2.0
prefix: 192.0.2.0/24
prefixlen: 24
```

We add `Prefix` nodes at multiple places, so this requires some work.

**Comment by romain-fontugne** [comment]
actually we can figure this out in post-processing, so if these fields are not given we could add them before dumping the database?

**Comment by m-appel** [comment]
Oh yeah, this makes way more sense. Let's create a new postprocessing
script for this.
