### ISSUE TITLE
DNS root zone file (IANA)

### ISSUE THREAD

**Issue by m-appel** [InternetHealthReport/internet-yellow-pages#82]
Data source: https://www.internic.net/domain/root.zone

We are interest in `A`, `AAAA`, and `NS` entries, which create the following relationships:

- `A`/`AAAA`: `(:DomainName)-[:RESOLVES_TO]->(:IP)`
- `NS`: `(:DomainName)-[:MANAGED_BY]->(:AuthoritativeNameServer)`

**Comment by m-appel** [comment]
This crawler requires update of the openintel crawlers at the same time, since it uses multi-label nodes. However, openintel already creates `AuthoritativeNameServer` nodes (without `DomainName` label) that overlap with nodes created by this crawler and since they miss the `DomainName` label there is a constraint error.

**Comment by romain-fontugne** [comment]
ok, I see. Should I fix the openintel crawler? Now that I have the new functions to add multilabels, I can try that.
