### ISSUE TITLE
RoVista RoV detection

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/internet-yellow-pages#83]
Get RoVista data from their API: https://api.rovista.netsecurelab.org/rovista/api/overview?offset=0&sortBy=rank&sortOrder=asc&count=1000&search=

This is paginated we should query it multiple times. All ASes with a ratio higher than 0.5 are categorized as 'Validating RPKI ROV' others are categorized 'Not Validating RPKI ROV'

So the added relationships are:
```cypher
(:AS)-[:CATEGORIZED {ratio: 1}]->(:Tag {label: 'Validating RPKI ROV')
```

and:
```cypher
(:AS)-[:CATEGORIZED {ratio: 0}]->(:Tag {label: 'Not Validating RPKI ROV')
```

**Comment by MAVRICK-1** [comment]
Below is a rough code snippet that fetches data from the RoVista API, categorizes ASes based on their ratio, and creates relationships accordingly using Neo4j's Python driver:

```python
import requests
from neo4j import GraphDatabase

# Neo4j connection parameters
uri = "neo4j://localhost:7687"
username = "neo4j"
password = "password"

# Neo4j query to create relationships
query = """
MATCH (tag:Tag {label: $label})
MATCH (as:AS {asn: $asn})
MERGE (as)-[:CATEGORIZED {ratio: $ratio}]->(tag)
"""

# Function to categorize ASes based on ratio and create relationships in Neo4j
def categorize_as(asn, ratio):
    if ratio > 0.5:
        label = 'Validating RPKI ROV'
    else:
        label = 'Not Validating RPKI ROV'
    with driver.session() as session:
        session.run(query, label=label, asn=asn, ratio=ratio)

# Fetch data from RoVista API and categorize ASes
def fetch_and_categorize():
    url = "https://api.rovista.netsecurelab.org/rovista/api/overview"
    params = {
        'offset': 0,
        'sortBy': 'rank',
        'sortOrder': 'asc',
        'count': 1000,
        'search': ''
    }
    response = requests.get(url, params=params)
    data = response.json().get('data', [])
    for entry in data:
        asn = entry['asn']
        ratio = entry['ratio']
        categorize_as(asn, ratio)

# Connect to Neo4j
driver = GraphDatabase.driver(uri, auth=(username, password))

# Call the function to fetch and categorize ASes
fetch_and_categorize()

# Close the Neo4j driver
driver.close()
```

@romain-fontugne @m-appel   is my approach right?
can u assign me this ?

**Comment by MAVRICK-1** [comment]
Below is a rough code snippet that fetches data from the RoVista API, categorizes ASes based on their ratio, and creates relationships accordingly 
```python
import requests
from neo4j import GraphDatabase

# Neo4j connection parameters
uri = "neo4j://localhost:7687"
username = "neo4j"
password = "password"



# Function to categorize ASes based on ratio and create relationships in Neo4j
def categorize_as(asn, ratio):
    if ratio > 0.5:
        query="""
            match (as:AS{asn:$asn}),(tag:Tag{label:"Validating RPKI ROV"})
            merge (as)-[:category{ratio:$ratio}]->(tag)
        """
    else:
        query="""
            match (as:AS{asn:$asn}),(tag:Tag{label:"Not Validating RPKI ROV"})
            merge (as)-[:category{ratio:$ratio}]->(tag)
        """
    with driver.session() as session:
        session.run(query, asn=asn, ratio=ratio)

# Fetch data from RoVista API and categorize ASes
def fetch_and_categorize():
    url = "https://api.rovista.netsecurelab.org/rovista/api/overview"
    params = {
        'offset': 0,
        'sortBy': 'rank',
        'sortOrder': 'asc',
        'count': 1000,
        'search': ''
    }
    response = requests.get(url, params=params)
    data = response.json().get('data', [])
    for entry in data:
        asn = entry['asn']
        ratio = entry['ratio']
        categorize_as(asn, ratio)

# Connect to Neo4j
driver = GraphDatabase.driver(uri, auth=(username, password))

# Call the function to fetch and categorize ASes
fetch_and_categorize()

# Close the Neo4j driver
driver.close()
```
@romain-fontugne @m-appel is my approach right?
can u assign me this ?

**Comment by m-appel** [comment]
Hey,
please take a look at [this crawler](https://github.com/InternetHealthReport/internet-yellow-pages/blob/main/iyp/crawlers/bgpkit/pfx2asn.py) for a simple example of how we usually write crawlers. There are already existing functions to create nodes and links in batches.

We are going to write/update some guidelines on how to write new crawlers soon™ where this will be described on more detail.

Your categorization is correct, but note that the example link only gives a page of 1000 entries, i.e., you will need to follow the pagination and fetch the remaining stuff as well.

**Comment by MAVRICK-1** [comment]
> Hey, please take a look at [this crawler](https://github.com/InternetHealthReport/internet-yellow-pages/blob/main/iyp/crawlers/bgpkit/pfx2asn.py) for a simple example of how we usually write crawlers. There are already existing functions to create nodes and links in batches.
> 
> We are going to write/update some guidelines on how to write new crawlers soon™ where this will be described on more detail.
> 
> Your categorization is correct, but note that the example link only gives a page of 1000 entries, i.e., you will need to follow the pagination and fetch the remaining stuff as well.

There was no function to set the property of relationship , So I created One https://github.com/MAVRICK-1/internet-yellow-pages/blob/RovDetection%2383/iyp/__init__.py#L562-L581
