### ISSUE TITLE
 Clarification on Database Dump Timelines at https://exp1.iijlab.net/wip/iyp/dumps/ 

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/internet-yellow-pages#84]
## Problem
I'm attempting to install Internet Yellow Pages on my local machine for experimentation. The project is intriguing, but I'm uncertain about the content of the database dumps available [here](https://exp1.iijlab.net/wip/iyp/dumps/). Specifically, I'm unsure whether these dumps contain all accumulated relationships since the initial publication of the database dump on `2022/12/09`, or if they only include the new relationships added between the previous dump and the latest one.

## Additional Context
My query stems from a desire to understand how the network relationships have evolved from, for instance, `2022/12/09`until the present. To achieve this, I'm seeking clarification on whether I should download all the database dumps or solely the most recent one.

**Comment by m-appel** [comment]
Thanks for your interest in IYP!

Each dump represents only a *snapshot* of all datasets. Keeping track of changes within the database, i.e., continuously updating it, would be too complicated with the amount of data we have and would also complicate queries.

So if you want to do a longitudinal analysis, you currently have to download multiple dumps.

**Comment by mohamedawnallah** [comment]
Thank you for answering my query; it makes sense!
